### ISSUE TITLE
UI parts?

### ISSUE THREAD

**Issue by Data-drone** [sicarul/shiny-chart-builder#1]
the commands in `config.R`:

This is for postgres example
```
UI_HEADER = commonHeader()
UI_THEME=baseTheme()
UI_STYLE=baseStyle()
UI_TITLE="Chart builder"
```

comes up with errors as it cannot find the functions `commonHeader(),` `baseTheme()`, `baseStyle()`
?

**Comment by xrocat** [comment]
I have the same problem. Don't find the function commonHeader()

**Comment by sicarul** [comment]
Sorry, wasn't watching my own repo :man_facepalming: 

You change it to the same as sqlite:

```
UI_HEADER =HTML("")
UI_THEME=NA
UI_STYLE=HTML("")
```

I'll change the examples to avoid confusion
